version: '3.8'

services:
  brain:
    build:
      context: ./brain
      dockerfile: Dockerfile
    container_name: financial_advisor_brain
    ports:
      - "8001:8001"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL:-https://api.deepseek.com}
      - DEEPSEEK_MODEL=${DEEPSEEK_MODEL:-deepseek-chat}
      - DEEPSEEK_TEMPERATURE=${DEEPSEEK_TEMPERATURE:-0.7}
      - DEEPSEEK_MAX_TOKENS=${DEEPSEEK_MAX_TOKENS:-2000}
      - BRAIN_PORT=8001
      - DEBUG=true
    volumes:
      - ./brain:/app:ro  # 开发模式：挂载代码目录
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial_advisor_backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_PORT=8000
      - BRAIN_SERVICE_URL=http://brain:8001
      - DATABASE_URL=sqlite:///./data/financial_advisor.db
      - DEBUG=true
    volumes:
      - ./web:/app/web:ro
      - ./backend:/app:ro  # 开发模式：挂载代码目录
      - ./backend_data:/app/data  # 数据库数据持久化
      - ./secure_uploads:/app/data/secure_uploads  # 安全用户上传文件持久化
    depends_on:
      brain:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: financial_advisor_network
