version: '3.8'

services:
  financial-advisor:
    build: .
    container_name: financial_advisor
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - financial_network

networks:
  financial_network:
    driver: bridge
